# Generated by Django 5.2.4 on 2026-03-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, db_index=True, help_text='Public order code for tracking (e.g. NG-2025-00123)', max_length=20, null=True, unique=True),
        ),
    ]
