# Generated by Django 6.0.3 on 2026-03-30 07:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0009_vendor_about_vendor_vendor_google_login_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('google_id', models.CharField(max_length=255)),
                ('profile_picture', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('default_address', models.TextField(blank=True)),
                ('default_pincode', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-last_login'],
                'constraints': [models.UniqueConstraint(fields=('email', 'vendor'), name='unique_buyer_email_per_vendor'), models.UniqueConstraint(fields=('google_id', 'vendor'), name='unique_buyer_google_per_vendor')],
            },
        ),
    ]
