"""
Django settings for nativeglow_backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from urllib.parse import urlparse
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-xhh0eb0ad)+o+eb2x$k0qu^#-eeci=%c9d)=o956*mfj-59nob',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = [
    host.strip()
    for host in config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())
    if host.strip()
]

render_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '').strip()
if render_hostname:
    ALLOWED_HOSTS.append(render_hostname)

if not DEBUG:
    ALLOWED_HOSTS.append('.onrender.com')

# Keep ordering stable while removing duplicates.
ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'channels',
    # NativeGlow apps
    'users',
    'vendors',
    'buyers',
    'products',
    'orders',
    'admins',
]

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'EXCEPTION_HANDLER': 'nativeglow_backend.exceptions.custom_exception_handler',
}

# JWT configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=15),
    'ROTATE_REFRESH_TOKENS': True,
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'nativeglow_backend.middleware.ApiJsonExceptionMiddleware',
]

# CORS — allow frontend dev server
CORS_ALLOWED_ORIGINS = [
    'https://native-glow.vercel.app',
    'https://www.native-glow.vercel.app',
    'http://localhost:3000',
    'http://localhost:5173',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:5173',
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r'^https://[a-z0-9-]+\.vercel\.app$',
]

CORS_ALLOW_HEADERS = list(
    {
        'accept',
        'accept-encoding',
        'authorization',
        'content-type',
        'dnt',
        'origin',
        'user-agent',
        'x-csrftoken',
        'x-requested-with',
        'x-device-id',
    }
)

extra_cors = config('CORS_ALLOWED_ORIGINS', default='', cast=Csv())
if extra_cors:
    CORS_ALLOWED_ORIGINS.extend(extra_cors)

CORS_ALLOWED_ORIGINS = list(dict.fromkeys(CORS_ALLOWED_ORIGINS))

CSRF_TRUSTED_ORIGINS = [
    'https://native-glow.vercel.app',
    'https://www.native-glow.vercel.app',
    'https://nativeglow.onrender.com',
]

extra_csrf_trusted = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())
if extra_csrf_trusted:
    CSRF_TRUSTED_ORIGINS.extend(extra_csrf_trusted)

CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))

SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

ROOT_URLCONF = 'nativeglow_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nativeglow_backend.wsgi.application'
ASGI_APPLICATION = 'nativeglow_backend.asgi.application'

redis_url = os.environ.get('REDIS_URL', '').strip()
if redis_url:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [redis_url]},
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

database_url = os.environ.get('DATABASE_URL', '').strip()
db_host = config('DB_HOST', default='localhost').strip()


def build_db_from_url(raw_url):
    parsed_db = urlparse(raw_url)
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': parsed_db.path.lstrip('/'),
        'USER': parsed_db.username,
        'PASSWORD': parsed_db.password,
        'HOST': parsed_db.hostname,
        'PORT': parsed_db.port or 5432,
        'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', default=60, cast=int),
        'OPTIONS': {
            'sslmode': config('DB_SSLMODE', default='require'),
            'connect_timeout': config('DB_CONNECT_TIMEOUT', default=10, cast=int),
        },
    }

if database_url:
    DATABASES = {
        'default': build_db_from_url(database_url)
    }
elif db_host.startswith('postgres://') or db_host.startswith('postgresql://'):
    DATABASES = {
        'default': build_db_from_url(db_host)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', default='nativeglow_db'),
            'USER': config('DB_USER', default='postgres'),
            'PASSWORD': config('DB_PASSWORD', default='postgres'),
            'HOST': db_host,
            'PORT': config('DB_PORT', default=5432, cast=int),
            'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', default=60, cast=int),
            'OPTIONS': {
                'sslmode': config('DB_SSLMODE', default='require'),
                'connect_timeout': config('DB_CONNECT_TIMEOUT', default=10, cast=int),
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Email Configuration
# Uses IPv4 forced SMTP backend & HTTP API fallback in production
_email_user = config('EMAIL_HOST_USER', default='').strip()
_has_http_key = bool(
    os.environ.get('RESEND_API_KEY') or os.environ.get('SENDGRID_API_KEY') or os.environ.get('BREVO_API_KEY')
)
_default_backend = (
    'nativeglow_backend.utils.IPv4SmtpEmailBackend'
    if (_email_user or _has_http_key)
    else 'django.core.mail.backends.console.EmailBackend'
)

_configured_backend = config('EMAIL_BACKEND', default=_default_backend).strip()
if _configured_backend in ('django.core.mail.backends.smtp.EmailBackend', ''):
    EMAIL_BACKEND = 'nativeglow_backend.utils.IPv4SmtpEmailBackend'
else:
    EMAIL_BACKEND = _configured_backend

DEFAULT_FROM_EMAIL = config(
    'DEFAULT_FROM_EMAIL',
    default=_email_user if _email_user else 'noreply@nativeglow.com'
)
DEFAULT_FROM_EMAILS = config('DEFAULT_FROM_EMAILS', default=DEFAULT_FROM_EMAIL)

EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com').strip()
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=30, cast=int)

_email_port = config('EMAIL_PORT', default=587)
try:
    EMAIL_PORT = int(str(_email_port).strip(' "\''))
except (ValueError, TypeError):
    EMAIL_PORT = 587

EMAIL_HOST_USER = _email_user
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='').strip()

_email_use_tls = config('EMAIL_USE_TLS', default=True)
EMAIL_USE_TLS = str(_email_use_tls).strip(' "\'').lower() in ['true', '1', 't', 'yes', 'y']

_email_use_ssl = config('EMAIL_USE_SSL', default=False)
EMAIL_USE_SSL = str(_email_use_ssl).strip(' "\'').lower() in ['true', '1', 't', 'yes', 'y']

# Auth integrations
GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID', default='')


