# Generated by Django 6.0.3 on 2026-03-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_contact_email_vendor_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payout_terms',
            field=models.CharField(default='Monthly settlement after service commission.', max_length=200),
        ),
    ]
