# Generated by Django 5.2.4 on 2026-03-23 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendor_bank_account_number_vendor_bank_ifsc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='commission_rate',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='fee_due_date',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='is_natural_certified',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='maintenance_status',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='monthly_fee_amount',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='payout_terms',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='product_types',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='state',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='status',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='store_slug',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='total_sales',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='website',
        ),
        migrations.RemoveField(
            model_name='vendorapplication',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='vendorapplication',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='vendorapplication',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='vendorapplication',
            name='user',
        ),
        migrations.AddField(
            model_name='vendor',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='maintenance_due',
            field=models.BooleanField(default=False, help_text='Monthly maintenance fee pending'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_slug',
            field=models.SlugField(blank=True, help_text='Used for product page URL', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='business_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='business_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval required'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='whatsapp_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorapplication',
            name='product_types',
            field=models.TextField(default='', help_text='Describe the types of natural products you sell'),
        ),
        migrations.AlterField(
            model_name='vendorapplication',
            name='why_collaborate',
            field=models.TextField(default='', help_text='Why do you want to partner with NativeGlow?'),
        ),
    ]
