# Generated by Django 6.0.3 on 2026-03-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_alter_maintenancepayment_id_alter_vendor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='natural_only_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='product_category',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vendor',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
