# Generated by Django 6.0.3 on 2026-03-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_vendor_natural_only_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='about_vendor',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='google_login_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vendor',
            name='redirect_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='site_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='site_banner_image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vendor',
            name='site_logo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vendor',
            name='site_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='site_theme',
            field=models.CharField(choices=[('default', 'Default'), ('minimal', 'Minimal'), ('bold', 'Bold'), ('elegant', 'Elegant')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='whatsapp_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
