# Generated by Django 5.2.4 on 2026-03-23 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
        ('vendors', '0006_alter_vendor_options_remove_vendor_bank_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, help_text='Format: YYYY-MM (e.g., 2025-03)', max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, default=500, help_text='Monthly platform fee', max_digits=10)),
                ('is_paid', models.BooleanField(db_index=True, default=False)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Vendor transaction ID / UTR', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_fees', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-month', '-created_at'],
                'indexes': [models.Index(fields=['month', 'is_paid'], name='admins_main_month_3cabe7_idx'), models.Index(fields=['vendor', 'is_paid'], name='admins_main_vendor__38c43b_idx')],
                'unique_together': {('vendor', 'month')},
            },
        ),
    ]
