# Generated by Django 6.0.3 on 2026-03-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_maintenancefee'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancefee',
            name='bank_reference_number',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='maintenancefee',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('net_banking', 'Net Banking')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenancefee',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance_proofs/'),
        ),
        migrations.AddField(
            model_name='maintenancefee',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancefee',
            name='upi_transaction_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='maintenancefee',
            name='verification_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenancefee',
            name='verified_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='maintenancefee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
