# Generated by Django 6.0.3 on 2026-03-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_maintenancefee_bank_reference_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(help_text='e.g., nativeglow@upi', max_length=120)),
                ('upi_name', models.CharField(help_text='e.g., NativeGlow Platform', max_length=255)),
                ('bank_account_number', models.CharField(max_length=60)),
                ('bank_ifsc', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Only one record should be active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Platform Payment Details',
                'ordering': ['-updated_at'],
            },
        ),
    ]
