# Generated by Django 6.0.3 on 2026-08-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_alter_adminuser_id_alter_maintenancefee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='active_device_id',
            field=models.CharField(blank=True, default='', help_text='The single device currently allowed to use this superadmin session', max_length=255),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email & Password'), ('google', 'Google OAuth2')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google OAuth2 subject (sub) identifier', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='maintenancefee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='platformpaymentdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
