# Generated by Django 6.0.3 on 2026-08-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_emailotp_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('vendor_apply', 'Vendor Apply'), ('buyer_login', 'Buyer Login')], max_length=30),
        ),
    ]
